# Generated by Django 3.2.6 on 2021-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useracct', models.CharField(max_length=128)),
                ('userpass', models.CharField(max_length=128)),
                ('useradrl', models.CharField(max_length=256, null=True)),
                ('usercrdt', models.DateTimeField(auto_now=True)),
                ('userupdt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
